### PR TITLE
Upgrade to 0.22-surveys

### PR DESCRIPTION
**Pull request by verarojman**
- [x] Upgrade to 0.22
- [x] Add new migrations
- [x] Add import line to fix scss dependency error
- [x] Add overrides spec and fix proposals markdown spec
- [x] Add rubocop config and correct rubocop offenses
- [x] Add markdown lint config 
- [x] Setup Lint and Test GitHub workflows

### CODE REVIEW

**Review by microstudi — CHANGES_REQUESTED** [review]
just ruby version!

**Comment by verarojman** [comment]
It's failing with this message, do you think we should add an ENV variable for `:here_app_id` in `.github/workflows/build.yml` ?
```
rails aborted!
KeyError: key not found: :here_app_id
Did you mean?  :here_api_key
```

**Comment by microstudi** [comment]
> @microstudi It's failing with this message, do you think we should add an ENV variable for `:here_app_id` in `.github/workflows/build.yml` ?
> 
> ```
> rails aborted!
> KeyError: key not found: :here_app_id
> Did you mean?  :here_api_key
> ```

Just in `config/secrets.yml` in the test section as dummy values

**Comment by microstudi** [comment]
Btw, no migrations from Decidim or the plugins?

**Review by microstudi — APPROVED** [review]
Great job @verarojman ! thanks a lot!

**Pull request merged**
